version: '3.8'

services:
  backend:
    build: ./backend
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      # Explicitly ensure no DATABASE_URL so Django uses SQLite
      - DATABASE_URL=

      # Django settings - no DATABASE_URL so it uses SQLite
      - DEBUG=1
      - SECRET_KEY=django-insecure-dev-secret-key-change-in-production
      - ALLOWED_HOSTS=localhost,127.0.0.1,backend,0.0.0.0

      # CORS settings for development
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://localhost:80,http://127.0.0.1:3000,http://127.0.0.1:80

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/auth/health/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api/v1
      - NODE_ENV=development
