# Generated by Django 5.2.7 on 2025-10-03 17:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_on_duty_hours', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('total_driving_hours', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('total_off_duty_hours', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('total_sleeper_berth_hours', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('cycle_start_date', models.DateField(blank=True, null=True)),
                ('available_hours_next_day', models.DecimalField(decimal_places=2, default=70, max_digits=4)),
                ('is_certified', models.BooleanField(default=False)),
                ('certified_at', models.DateTimeField(blank=True, null=True)),
                ('has_supporting_documents', models.BooleanField(default=False)),
                ('document_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('certified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certified_logs', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hos_daily_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('driver', 'date')},
            },
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('duty_status', models.CharField(choices=[('off_duty', 'Off Duty'), ('sleeper_berth', 'Sleeper Berth'), ('driving', 'Driving'), ('on_duty_not_driving', 'On Duty (Not Driving)')], max_length=30)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('total_hours', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('vehicle_info', models.CharField(blank=True, help_text='Vehicle identification', max_length=255)),
                ('trailer_info', models.CharField(blank=True, help_text='Trailer identification', max_length=255)),
                ('odometer_start', models.DecimalField(blank=True, decimal_places=1, help_text='Starting odometer reading', max_digits=8, null=True)),
                ('odometer_end', models.DecimalField(blank=True, decimal_places=1, help_text='Ending odometer reading', max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hos_log_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-start_time'],
                'unique_together': {('driver', 'date', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(choices=[('driving_limit', '11-hour Driving Limit'), ('on_duty_limit', '14-hour On-duty Limit'), ('rest_requirement', '10-hour Rest Requirement'), ('cycle_limit', '70/8 or 60/7 Cycle Limit'), ('falsification', 'Log Falsification'), ('missing_logs', 'Missing Required Logs')], max_length=50)),
                ('description', models.TextField()),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('severity', models.CharField(default='minor', max_length=20)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('daily_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logs.dailylog')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hos_violations', to=settings.AUTH_USER_MODEL)),
                ('log_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logs.logentry')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
    ]
