# Generated by Django 5.2.7 on 2025-10-03 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='odometer_end',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Ending odometer reading', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='logentry',
            name='odometer_start',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Starting odometer reading', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='logentry',
            name='trailer_info',
            field=models.CharField(blank=True, help_text='Trailer identification', max_length=255),
        ),
        migrations.AddField(
            model_name='logentry',
            name='vehicle_info',
            field=models.CharField(blank=True, help_text='Vehicle identification', max_length=255),
        ),
    ]
