# Generated by Django 5.2.7 on 2025-10-03 10:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_alter_trip_driver'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={},
        ),
        migrations.AddField(
            model_name='trip',
            name='is_automatic',
            field=models.BooleanField(default=False, help_text='Automatically created trip'),
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date this trip represents'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='current_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_trips', to='trips.location'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='dropoff_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dropoff_trips', to='trips.location'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='name',
            field=models.CharField(blank=True, help_text='Auto-generated trip name', max_length=255),
        ),
        migrations.AlterField(
            model_name='trip',
            name='pickup_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_trips', to='trips.location'),
        ),
    ]
