# Generated by Django 5.2.7 on 2025-10-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='auto_close_trip_at_midnight',
            field=models.BooleanField(default=True, help_text='Automatically close current trip and start new one at midnight'),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='auto_close_trip_time',
            field=models.TimeField(default='00:00:00', help_text="Time to automatically close current trip (in driver's timezone)"),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='default_cycle',
            field=models.CharField(choices=[('70_8', '70 hours / 8 days'), ('60_7', '60 hours / 7 days')], default='70_8', max_length=10),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='timezone',
            field=models.CharField(default='America/New_York', help_text='Timezone for trip and log management', max_length=50),
        ),
    ]
